openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
  description: API for managing contacts (CSE 341 Project)

servers:
  - url: https://cse-341-project1-1-oct6.onrender.com

paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Get all contacts
      responses:
        '200':
          description: A list of contacts
    post:
      tags:
        - Contacts
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          description: Contact created
        '400':
          description: Invalid request body

  /contacts/{id}:
    get:
      tags:
        - Contacts
      summary: Get a single contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single contact
        '404':
          description: Contact not found

    put:
      tags:
        - Contacts
      summary: Update a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '204':
          description: Contact updated
        '404':
          description: Contact not found
        '400':
          description: Invalid update data

    delete:
      tags:
        - Contacts
      summary: Delete a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Contact deleted
        '404':
          description: Contact not found

components:
  schemas:
    Contact:
      type: object
      required:
        - firstName
        - lastName
        - email
        - favoriteColor
        - birthday
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        favoriteColor:
          type: string
        birthday:
          type: string
          format: date
